services:
    rj_frontend.asset.package.path:
        class: Symfony\Component\Asset\PathPackage
        public: false

    rj_frontend.asset.package.url:
        class: Symfony\Component\Asset\UrlPackage
        public: false
