services:
    rj_frontend.asset.package.path:
        class: Rj\FrontendBundle\Asset\PathPackage
        public: false

    rj_frontend.asset.package.url:
        class: Rj\FrontendBundle\Asset\UrlPackage
        public: false

    rj_frontend.asset.package.fallback:
        class: Rj\FrontendBundle\Asset\FallbackPackage
        public: false
